# Generated by Django 4.2.4 on 2023-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('qtt', models.IntegerField(verbose_name='Quantité')),
                ('destinationCompte', models.CharField(choices=[('MGX', 'Moyens Généraux'), ('INT', 'Interconnexions')], default='MGX', max_length=15, verbose_name='Compte de Destination')),
                ('natureAchat', models.CharField(choices=[('001', 'Investissement'), ('002', 'Service'), ('003', 'Consommable'), ('004', 'Autre')], default='001', max_length=14, verbose_name="Nature de l'Achat")),
                ('miseDiso', models.CharField(choices=[('001', 'Cosommable interne'), ('002', 'Revente client'), ('003', 'Stock'), ('004', 'Autre')], default='001', max_length=18)),
                ('affectationAchat', models.CharField(choices=[('001', 'Famille accés internet'), ('002', 'Famille Communication unifié'), ('003', 'Famille CLOUD')], default='001', max_length=30, verbose_name="Affectation de l'Achat")),
            ],
        ),
    ]
