# Generated by Django 4.2.4 on 2023-08-29 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_produit', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=250)),
                ('date_de_la_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_de_la_demande')),
                ('service', models.CharField(choices=[('Moyens généraux', 'Moyens généraux'), ('Interco', 'Interco')], default='Moyens généraux', max_length=15)),
            ],
        ),
    ]
