# Generated by Django 4.2.4 on 2023-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predemande',
            name='activee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='predemande',
            name='validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='predemande',
            name='md_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='predemande',
            name='na_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
