# Generated by Django 4.2.4 on 2023-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predemande',
            name='activee',
        ),
        migrations.RemoveField(
            model_name='predemande',
            name='validee',
        ),
        migrations.AddField(
            model_name='predemande',
            name='statut',
            field=models.CharField(choices=[('001', 'Validée'), ('002', 'Rejetée'), ('003', 'En cours'), ('004', 'Annulée'), ('005', 'Clôturée')], default='003', max_length=10, verbose_name='Statut'),
        ),
    ]
