# Generated by Django 4.2.4 on 2023-09-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_user_email_alter_user_matricule'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predemande',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comptes.structure'),
        ),
    ]
