# Generated by Django 4.2.4 on 2023-09-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predemande',
            name='md_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='predemande',
            name='na_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='predemande',
            name='miseDiso',
            field=models.CharField(choices=[('001', 'Consommable interne'), ('002', 'Revente client'), ('003', 'Stock'), ('004', 'Autre')], default='001', max_length=18, verbose_name='miseDispo'),
        ),
    ]
