# Generated by Django 4.2.4 on 2023-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_predemande_reponse_finale_alter_predemande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predemande',
            name='statut',
            field=models.CharField(choices=[('001', 'En cours'), ('002', "Annulée par l'utilisateur"), ('003', 'Validée par le directeur de la structure'), ('004', 'Clôturée')], default='001', max_length=40, verbose_name='Statut'),
        ),
    ]
