# Generated by Django 4.2.4 on 2023-09-17 20:32

import achat.models.comptecomptable
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_comptable', models.CharField(max_length=6, unique=True, validators=[achat.models.comptecomptable.CompteComptable.only_int])),
                ('nom_compte', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompteComptableDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_detail', models.CharField(max_length=250)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('destination_achat_compte', models.CharField(choices=[('MGX', 'Moyens Généraux'), ('INT', 'Interconnexions')], default='MGX', max_length=80)),
                ('devise', models.CharField(choices=[('DZD', 'Dinars Algérienne'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='DZD', max_length=40)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('code_comptable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compte_detail', to='achat.comptecomptable')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compte_direction', to='comptes.structure')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DA_Code', models.CharField(blank=True, default='_', max_length=50)),
                ('destination_achat', models.CharField(choices=[('MGX', 'Moyens Généraux'), ('INT', 'Interconnexions')], max_length=128)),
                ('nature_achat', models.CharField(choices=[('001', 'Investissement'), ('002', 'Service'), ('003', 'Consommable'), ('004', 'Autre')], max_length=128)),
                ('autre_nature_achat', models.CharField(max_length=255, null=True)),
                ('mise_dispo', models.CharField(choices=[('001', 'Cosommable interne'), ('002', 'Revente client'), ('003', 'Stock'), ('004', 'Autre')], max_length=128)),
                ('autre_mise_dispo', models.CharField(max_length=255, null=True)),
                ('affectation_achat', models.CharField(choices=[('001', 'Famille accés internet'), ('002', 'Famille Communication unifié'), ('003', 'Famille CLOUD'), ('005', 'Autre')], max_length=128)),
                ('autre_affectation_achat', models.CharField(max_length=255, null=True)),
                ('total_devis', models.DecimalField(decimal_places=3, max_digits=50, null=True)),
                ('devise', models.CharField(choices=[('autre', '----------'), ('DZD', 'Dinars Algérienne'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='autre', max_length=40)),
                ('disponibilité', models.CharField(choices=[('OUI', 'DISPONIBLE'), ('NON', 'NON DISPONIBLE')], default='OUI', max_length=20)),
                ('bon_commande', models.CharField(max_length=25, null=True)),
                ('statut_achat', models.CharField(choices=[('001', 'En cours'), ('003', 'Clôturé'), ('002', 'Annulé')], max_length=128)),
                ('detail_statut_achat', models.CharField(max_length=255, null=True)),
                ('etat_achat', models.CharField(max_length=255, null=True)),
                ('note_achat', models.TextField()),
                ('validation_dg', models.BooleanField(default=False)),
                ('autre_validation', models.TextField(default=False)),
                ('validation_directeur', models.BooleanField(default=False)),
                ('Date_valid_directeur', models.DateTimeField(null=True)),
                ('Date_valid_dg', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('code_comptable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.comptecomptable')),
                ('code_comptable_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.comptecomptabledetails')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=250)),
                ('id_enregistrement', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_projet', models.CharField(max_length=20)),
                ('nom_projet', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_chef', to=settings.AUTH_USER_MODEL)),
                ('compte_comptable_detail', models.ManyToManyField(related_name='list_compte_detail', to='achat.comptecomptabledetails')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.FloatField()),
                ('fournisseur', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=50)),
                ('id_achat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_achat', to='achat.demandeachat')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralHistoricalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=250)),
                ('new_data', models.JSONField(verbose_name=dict)),
                ('old_data', models.JSONField(verbose_name=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_create_by', to=settings.AUTH_USER_MODEL)),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_historique', to='achat.generalhistorical')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('demande_achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.demandeachat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_DP', models.CharField(blank=True, default='*/2022', max_length=50)),
                ('Num_fournisseur', models.CharField(blank=True, default='0', max_length=50)),
                ('beneficiaire', models.CharField(blank=True, default='xxx', max_length=250)),
                ('bon_commande', models.CharField(blank=True, default='xxx', max_length=250)),
                ('num_facture', models.CharField(blank=True, default='xxx', max_length=250)),
                ('montant_chiffre', models.DecimalField(decimal_places=3, max_digits=50, null=True)),
                ('montant_lettres', models.CharField(blank=True, default='xxx', max_length=250)),
                ('devise', models.CharField(default='DZD', max_length=40)),
                ('mode_paiment', models.CharField(choices=[('001', 'Espèce'), ('002', 'Chèque'), ('003', 'Virement')], default='001', max_length=20)),
                ('Num_compte', models.CharField(blank=True, default='xxx', max_length=80)),
                ('rib', models.CharField(blank=True, default='xxx', max_length=80)),
                ('adresse', models.CharField(blank=True, default='xxx', max_length=250)),
                ('swift', models.CharField(blank=True, default='xxx', max_length=80)),
                ('objet_paiment', models.CharField(max_length=255, null=True)),
                ('document_DP', models.FileField(null=True, upload_to='documents/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by', to=settings.AUTH_USER_MODEL)),
                ('demande_achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.demandeachat')),
            ],
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.project'),
        ),
    ]
