# Generated by Django 4.2.4 on 2023-09-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='comptes.structure'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
