# Generated by Django 4.2.4 on 2023-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricule',
            field=models.CharField(max_length=20, verbose_name='Matricule'),
        ),
    ]
